### ISSUE TITLE
Version mismatch between d3 and plugins caused UE editor to crash

### ISSUE THREAD

**Issue by makkbe** [disguise-one/RenderStream-UE#14] opened 2021-06-24 19:00 UTC
**Current behavior**
When there is a version mismatch between d3 and the RenderStream plugin, this causes the UE editor to crash when launched without an error message, making troubleshooting difficult. 

**Expected behavior**
UE editor should not crash, and present an informative error message to the user.

**Comment by MunWolf** [comment] 2021-06-30 11:19
This may have been fixed already in later versions, if we could please get the plugin and d3 version where this happens so we can reproduce or backport the fixes if the issue is still there in specific versions.

**Comment by BildInstaller** [comment] 2021-06-30 12:37
I had this issue on the Plugin version 1.25 and d3 version 79811, the Editor when to 9% and crashed out. 

Jamie from Bild

**Comment by husberg-disguise** [comment] 2021-08-13 09:37
The cause is an abort in the d3renderstream.dll due to the FreeLibrary call in RenderStreamLink::unloadExplicit. Logged internally as DSOF-17908

**Comment by husberg-disguise** [comment] 2021-09-08 12:34
Fixed in r19.2

**Closed as completed by husberg-disguise** 2021-09-08 12:34 UTC
Labels: bug, question
